# Generated by Django 5.0.2 on 2024-02-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeddata',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
